use_frameworks!

platform :ios, '10.0'

target 'POD_SPM_lib_Example' do
  pod 'POD_SPM_lib', :path => '../'

  target 'POD_SPM_lib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
